CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FFE2A0D1_DAF7_41F7_9325_7C7604CC1D8E" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_18239D7D_2AF0_4118_A4A2_A4B1E5A15019" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_716AE18C_0B50_45F1_B7B2_74FE5DEE6734" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D8BCFFAB_750C_4274_A72B_C21EB2061F87" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."COMPANY"(
    "COMPANY_ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_FFE2A0D1_DAF7_41F7_9325_7C7604CC1D8E" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FFE2A0D1_DAF7_41F7_9325_7C7604CC1D8E",
    "ADDRESS" VARCHAR(255),
    "CREATED_AT" TIMESTAMP,
    "TVA_NUMBER" BIGINT NOT NULL,
    "UPDATED_AT" TIMESTAMP,
    "UUID" uuid default random_uuid()
);
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("COMPANY_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMPANY;
CREATE MEMORY TABLE "PUBLIC"."CONTACT"(
    "CONTACT_ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_18239D7D_2AF0_4118_A4A2_A4B1E5A15019" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_18239D7D_2AF0_4118_A4A2_A4B1E5A15019",
    "ADDRESS" VARCHAR(255),
    "CONTACT_TYPE" VARCHAR(255) NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "FIRSTANME" VARCHAR(255),
    "LASTNAME" VARCHAR(255),
    "TVA_NUMBER" BIGINT,
    "UPDATED_AT" TIMESTAMP,
    "UUID" uuid default random_uuid()
);
ALTER TABLE "PUBLIC"."CONTACT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_63" PRIMARY KEY("CONTACT_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONTACT;
CREATE MEMORY TABLE "PUBLIC"."CONTACTS_COMPANIES"(
    "CONTACT_ID" INTEGER NOT NULL,
    "COMPANY_ID" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."CONTACTS_COMPANIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("CONTACT_ID", "COMPANY_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONTACTS_COMPANIES;
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ROLE_ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_716AE18C_0B50_45F1_B7B2_74FE5DEE6734" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_716AE18C_0B50_45F1_B7B2_74FE5DEE6734",
    "NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ROLE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "USER_ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D8BCFFAB_750C_4274_A72B_C21EB2061F87" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D8BCFFAB_750C_4274_A72B_C21EB2061F87",
    "FIRSTNAME" VARCHAR(255),
    "LASTNAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("USER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
CREATE MEMORY TABLE "PUBLIC"."USERS_ROLES"(
    "USER_ID" INTEGER NOT NULL,
    "ROLE_ID" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."USERS_ROLES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("USER_ID", "ROLE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS_ROLES;
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."UK_2WNS5COD7F1485CJWCIXV1843" UNIQUE("TVA_NUMBER");
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."UK_8SEWWNPAMNGI6B1DWAA88ASKK" UNIQUE("NAME");
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."UK_SB8BBOUER5WAK8VYIIY4PF2BX" UNIQUE("USERNAME");
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."UK_JOTWD7HX1GSPOGEY1BEDHGE7R" UNIQUE("UUID");
ALTER TABLE "PUBLIC"."CONTACT" ADD CONSTRAINT "PUBLIC"."UK_4FWVE81LUV6KMESFIF3W9174C" UNIQUE("UUID");
ALTER TABLE "PUBLIC"."USERS_ROLES" ADD CONSTRAINT "PUBLIC"."FKGD3IENDAOYH04B95YKQISE6QH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("USER_ID") NOCHECK;
ALTER TABLE "PUBLIC"."CONTACTS_COMPANIES" ADD CONSTRAINT "PUBLIC"."FKAYX3VTQV750TV2ITBQOCXI80G" FOREIGN KEY("CONTACT_ID") REFERENCES "PUBLIC"."CONTACT"("CONTACT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."CONTACTS_COMPANIES" ADD CONSTRAINT "PUBLIC"."FKLS6T0AQ4IOMT49L48K150NM7K" FOREIGN KEY("COMPANY_ID") REFERENCES "PUBLIC"."COMPANY"("COMPANY_ID") NOCHECK;
ALTER TABLE "PUBLIC"."USERS_ROLES" ADD CONSTRAINT "PUBLIC"."FKT4V0RRWEYK393BDGT107VDX0X" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ROLE_ID") NOCHECK;
